shutdown immediate;
startup mount;
alter database archivelog;
ALTER SESSION SET SQL_TRACE=TRUE;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
ALTER SYSTEM SET AQ_TM_PROCESSES=0;
alter database open;
ALTER DATABASE CHARACTER SET INTERNAL_USE ZHT16BIG5;
ALTER SESSION SET SQL_TRACE=FALSE;
archive log list;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

CREATE TABLESPACE LOGMINER_TBS DATAFILE '/u01/app/oracle/oradata/XE/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE USER logminer IDENTIFIED BY logminer DEFAULT TABLESPACE LOGMINER_TBS QUOTA UNLIMITED ON LOGMINER_TBS;
GRANT CREATE SESSION TO logminer;
GRANT SELECT ON V_$DATABASE TO logminer;
GRANT FLASHBACK ANY TABLE TO logminer;
GRANT SELECT ANY TABLE TO logminer;
GRANT SELECT_CATALOG_ROLE TO logminer;
GRANT EXECUTE_CATALOG_ROLE TO logminer;
GRANT SELECT ANY TRANSACTION TO logminer;
GRANT SELECT ANY DICTIONARY TO logminer;
GRANT CREATE TABLE TO logminer;
GRANT ALTER ANY TABLE TO logminer;
GRANT LOCK ANY TABLE TO logminer;

CREATE TABLESPACE GRAVITY_TBS DATAFILE '/u01/app/oracle/oradata/XE/gravity_tbs.dbf' SIZE 50M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE USER gravity IDENTIFIED BY gravity DEFAULT TABLESPACE GRAVITY_TBS QUOTA UNLIMITED ON GRAVITY_TBS;
GRANT CONNECT, RESOURCE TO gravity;
GRANT UNLIMITED TABLESPACE TO gravity;
GRANT CREATE SEQUENCE to gravity;

CREATE TABLE GRAVITY.users (
    ID          VARCHAR(36) PRIMARY KEY,
    USERNAME    VARCHAR(20),
    PASSWORD    VARCHAR(64),
    NAME        VARCHAR(40),
    EMAIL       VARCHAR(80),
    PHONE       VARCHAR(50),
    ADDRESS     VARCHAR(512),
    JOIN_TIME   TIMESTAMP
);
